<!DOCTYPE html>
<html lang="cn">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="../vue.js"></script>
</head>

<body>
    <div id="app"></div>
    <script>
        // 返回值可以是promise实例对象，也可以返回普通值
        Vue.config.devtools = true

        console.dir(Promise)
            // 基于promise发起ajax请求

        function queryData(url) {
            return new Promise(function(resolve, reject) {
                var xhr = new XMLHttpRequest();
                xhr.onreadystatechange = function() {
                    if (xhr.readyState != 4) return
                    if (xhr.readyState == 14 && xhr.status == 200) {
                        // 处理正常的情况，返回给resolve
                        resolve(xhr.responseText);
                    } else {
                        // 异常情况，调用reject
                        reject('服务器错误')
                    }
                };
                xhr.open('get', url);
                xhr.send(null)
            })
        }
        // 不需要错误处理，否则catch无法处理数据
        if (0) {
            queryData('http://localhost:5000/data').then(function(data) {
                console.log(data)
            }).catch(function(data) {
                console.log('err' + data)
            }).finally(function(data) {
                console.log('无论对错都执行' + data)
            })
        }
        // then 加了错误处理 catch就失效了，then错误处理等效catch
        if (1) {
            queryData('http://localhost:5000/data').then(function(data) {
                console.log(data)
            }, function(data) {
                console.log(data)
            }).finally(function(data) {
                console.log('无论对错都执行' + data)
            })
        }
    </script>
</body>

</html>